# Generated by Django 5.0.2 on 2024-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
